[aws]
disabled = false
format = '[$symbol$profile-$region]($style) '
style = 'italic yellow'
symbol = '󰸏 '

[golang]
symbol = ' '
disabled = false

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '	
style = 'italic purple'

[docker_context]
disabled = true

[python]
disabled = true

[package]
disabled = true

[time]
disabled = true
style = 'dimmed bold italic #008080'
format = '[$time]($style) '

[cmd_duration]
disabled = true
